object_store_addresses:
  - unix7.andrew.cmu.edu
  - unix8.andrew.cmu.edu

# Only changing the port for cassandra is not enough.
# port in cassandra.yaml has to be changed as well.
object_store_port: 9346
object_store_cache_redis_port: 6380

num_logical_volumes: 2

# This number should be less or equal to the number of object store addresses
store_replication_factor: 2

object_cache_addresses:
  - unix5.andrew.cmu.edu
#  - unix6.andrew.cmu.edu

directory_address: unix4.andrew.cmu.edu
directory_port: 9346
directory_cache_redis_port: 6380

# port for web server
web_server_port: 9876
object_cache_port: 9876